# Generated by Django 5.1 on 2024-08-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='dob',
            field=models.DateTimeField(max_length=240, null=True),
        ),
    ]
