# Generated by Django 5.1 on 2024-08-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appuser_age_alter_appuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_logined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
