# Generated by Django 5.1 on 2024-08-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appuser_last_logined'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
