# Generated by Django 5.1 on 2024-08-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='count',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
