# Generated by Django 5.1 on 2024-08-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_paren_categoryt',
            new_name='sub_parent_category',
        ),
    ]
