# Generated by Django 5.1 on 2024-08-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_sub_paren_categoryt_category_sub_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_parent_category',
        ),
    ]
