# Generated by Django 5.1 on 2024-08-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_category_sub_parent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_parent_category',
        ),
    ]
