# Generated by Django 5.1 on 2024-08-15 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_category_sub_parent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=10)),
                ('category_is', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('group_is', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.group')),
            ],
        ),
    ]
