# Generated by Django 5.1 on 2024-08-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_notification_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_db',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
