# Generated by Django 5.1 on 2024-08-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_notification_db_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='count',
        ),
    ]
