# Generated by Django 5.1 on 2024-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_group_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='group_is',
        ),
        migrations.AddField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(related_name='app_users', to='app.group'),
        ),
    ]
