# Generated by Django 5.1 on 2024-08-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_appuser_group_is_appuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='group_is',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
    ]
