# Generated by Django 5.1 on 2024-08-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_appuser_group_is_alter_appuser_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='group_is',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
