# Generated by Django 5.1 on 2024-09-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_appuser_designation_alter_pdffiles_category_is_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, null=True)),
                ('app_url', models.CharField(max_length=100, null=True)),
                ('app_icon', models.FileField(blank=True, null=True, upload_to='app_icons/')),
                ('color', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=10)),
            ],
        ),
    ]
