# Generated by Django 5.1.1 on 2024-10-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_apps_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_sign',
            field=models.FileField(blank=True, null=True, upload_to='user_sign/'),
        ),
    ]
