# Generated by Django 5.1.1 on 2024-11-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_appuser_user_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_ref_no', models.CharField(max_length=100, null=True)),
                ('form_Id', models.CharField(max_length=100, null=True)),
                ('form_Name', models.CharField(max_length=240, null=True)),
                ('form_Date', models.DateField(blank=True, null=True)),
                ('formData', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=10)),
                ('Aircraft_Reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft_reg', to='app.group')),
                ('Aircraft_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft_type', to='app.group')),
                ('user_is', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appuser')),
            ],
        ),
    ]
