# Generated by Django 5.1.1 on 2025-01-06 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_forms_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignPDFFiles_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signfile_Id', models.CharField(max_length=100, null=True)),
                ('signfile_Name', models.CharField(max_length=240, null=True)),
                ('signfile_Date', models.DateField(blank=True, null=True)),
                ('signature_count', models.CharField(default='0', max_length=10)),
                ('signpdf_file', models.FileField(blank=True, null=True, upload_to='sign-pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=10)),
                ('Aircraft_Reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signaircraft_reg', to='app.group')),
                ('Aircraft_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signaircraft_type', to='app.group')),
            ],
        ),
        migrations.CreateModel(
            name='SignedCaptFiles_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signedpdf_file', models.FileField(blank=True, null=True, upload_to='captsigned-files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=10)),
                ('user_is', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appuser')),
                ('signFile_is', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.signpdffiles_db')),
            ],
        ),
    ]
