# Generated by Django 5.1.1 on 2025-02-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_signpdffiles_db_signedcaptfiles_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='weight',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
